### ISSUE TITLE
Modify scraper to use date on webpage in CSV instead of current date

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/colly-draft-prospects#6]
On page 1, there's a date signifying the last time the rankings were updated.

The inner HTML looks something like this:
`(October 14, 2018) 2019 NFL Draft Big Board: Top-300`
CSS Selector: #calloutwifnba > strong:nth-child(1)
CSS Path: html body div#outer div#wrapper div#content div#calloutwifnba strong
XPath: /html/body/div[1]/div[3]/div[2]/div/strong

Get the date from the page.  Put it in the format YYYY-MM-DD and write it in the output CSV instead of the current date.  Keep the Current Date output for the CSV file name.

**Comment by ulziibuyan** [comment]
Imma give this a go.

**Comment by zo0o0ot** [comment]
#9 closes #6.
